<div style="margin-bottom: 120px;">
    <div style="float:left;">
        <br/>
        <img src="notebooks-img/udc.png" width="300"/>
    </div>
</div>


<h1 style="color: #d60e8c; text-align:center;">Vectores y matrices con NumPy</h1> 


<h2>Contenidos</h2>
<div class="alert alert-block alert-info" 
     style="margin-top: 0px; padding-top:0px; border: 1px solid #d60e8c; border-radius: 20px; background:transparent;">
    <ul>
        <li><a href="#intro">Introducción</a></li>
        <li><a href="#arrays">Arrays</a></li>      
        <li><a href="#operaciones">Operaciones con arrays</a></li>                
        <li><a href="#matrices">Matrices</a></li>        
        <li><a href="#opmatrices">Operaciones con matrices</a></li>     
        <li><a href="#ejemplo">Ejemplo de ejercicio con matrices</a></li>     
    </ul>
</div>

<a name="intro"></a>

<h2 style="color: #d60e8c;">Introducción</h2>
<hr style="border: 0.5px solid #d60e8c;">

- NumPy es el paquete de cálculo por excelencia en Python. 
- Muchos otros, más específicos, lo utilizan como base => SciPy, pandas, scikit-image, Matplotlib, Seaborn...
- Características principales:
    - Está implementado en C => **eficiencia**
    - El tipo de dato básico es el array n-dimensional donde **todos los elementos son del mismo tipo**.
    - Al contrario que al trabajar con listas, las funciones de NumPy devuelven **vistas** siempre que es posible


En este cuaderno se incluyen alguna de las funciones de NumPy pero no pretende ser una guía de referencia sino una introducción para conocer la librería y aprender a utilizar alguna de sus operaciones. La documentación de referencia debería ser siempre la documentación oficial de NumPy donde se puede consultar de forma de detallada cada uno de los tipos y operaciones disponibles. 

Estos son los enlaces a la documentación de referencia y a un tutorial de NumPy:

- <a href="https://numpy.org/doc/stable/index.html">Documentación oficial de NumPy</a>
- <a href="https://numpy.org/doc/stable/user/absolute_beginners.html">Tutorial para aprender NumPy desde cero</a>




<h3 style="color: #d60e8c;">Antes de comenzar </h3>

En los siguientes apartados veremos ejemplo de algunas funciones. Para comenzar y poder utilizar NumPy, antes hay que importar el módulo:

In [1]:
import numpy as np  # "as" se utiliza para usar el nombre np en nuestro programa en lugar de numpy

<a name="arrays"></a>
<h2 style="color: #d60e8c;">Arrays: creación y propiedades</h2>
<hr style="border: 0.5px solid #d60e8c;">

<h3 style="color: #d60e8c;">Creación de arrays</h3>

| Función | Descripción |
| :-- | :-- |
| array(*list*) | array a partir de una lista |
| zeros(*shape*) | array relleno con ceros de la forma indicada|
| ones(*shape*) | array relleno con unos de la forma indicada|
| empty(*shape*) | array **sin inicializar** (*) de la forma indicada|
| arange(*start, end, step=1*) | crea un array de 1 dimensión desde start hasta end con el intervalo determinado (por defecto 1) |
| linspace(*start, end, num=50*) | crea un array de 1 dimensión desde start hasta end dividido en el número de elementos determinado (por defecto 50)|


(*) **Sin inicializar** significa que el array que crea empty no se rellena al crearlo con valores determinados, tendrá valores cualquiera que no significan nada, lo usaremos
    cuando queramos crear un array vacío para rellenarlo después con otros valores. También podríamos utilizar zeros
    o ones pero como ya vamos a rellenarlo con los valores que queremos sería un poco menos eficiente porque estos
    arrays sí se inicializan, a ceros y unos, respectivamente.

<h3 style="color: #d60e8c;">Propiedades de los arrays</h3>

| Propiedad | Devuelve  | Descripción |
| :-- | :-- | :-- |
| ndim | int |  número de dimensiones (ejes) |
| shape |  tupla |  Forma del array (longitud de cada dimension) |
| size | int | Número de elementos |
| dtype| dtype | Tipo de los elementos |

<h3 style="color: #d60e8c;">Vectores: 1 dimensión</h3>


In [7]:
vector = np.array([2, 1, 5, 3, 7, 4, 6, 8], dtype=np.int64)  # Se puede indicar el tipo de los elemento
ceros = np.zeros(2)
unos = np.ones(2)
vacio = np.empty(2)
interv1 = np.arange(2, 9, 2)
interv2 = np.linspace(0, 10, num=5)

In [3]:
print(f"vector: {vector}")
print(f"ceros: {ceros}")
print(f"unos: {unos}")
print(f"vacio: {vacio}")   # Puede contener cualquier valor, no está inicializado
print(f"interv1: {interv1}")
print(f"interv2: {interv2}")

vector: [2 1 5 3 7 4 6 8]
ceros: [0. 0.]
unos: [1. 1.]
vacio: [-2.31584178e+77 -2.31584178e+77]
interv1: [2 4 6 8]
interv2: [ 0.   2.5  5.   7.5 10. ]


Ejemplo de propiedades de los arrays sobre el array al que hemos llamado "vector":

In [13]:
print(f"Número de dimensiones: {vector.ndim}")
print(f"Forma: {vector.shape}")
print(f"Tamaño: {vector.size}")
print(f"Tipo de dato de los elementos: {vector.dtype}")

Número de dimensiones: 1
Forma: (8,)
Tamaño: 8
Tipo de dato de los elementos: int64


<h3 style="color: #d60e8c;">Matrices: 2 dimensiones</h3>

In [10]:
matriz = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
identidad = np.identity(2)

In [11]:
print(f"matriz: \n{matriz}")
print(f"identidad: \n{identidad}")

matriz: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
identidad: 
[[1. 0.]
 [0. 1.]]


Ejemplo de propiedades de los arrays sobre el array al que hemos llamado "matriz":

In [14]:
print(f"Número de dimensiones: {matriz.ndim}")
print(f"Forma: {matriz.shape}")
print(f"Tamaño: {matriz.size}")
print(f"Tipo de dato de los elementos: {matriz.dtype}")

Número de dimensiones: 2
Forma: (3, 4)
Tamaño: 12
Tipo de dato de los elementos: int64


<a name="operaciones"></a>
<h2 style="color: #d60e8c;">Operaciones con arrays</h2>
<hr style="border: 0.5px solid #d60e8c;">

<h3 style="color: #d60e8c;">Operaciones matemáticas</h3>

| Método | Descripción |
| :-- | :-- |
| .max()  | Devuelve el valor máximo del array|
| .min()  | Devuelve el valor mínimo del array|
| .argmax() | Devuelve el índice del valor máximo |
| .argmin() | Devuelve el índice del valor mínimo |
| .sum() | Suma de los elementos del array |
| .mean()  | Media de los de los elementos del array  |
| .std() | Desviación estándar de los elementos del array |
| .cumsum() | Array con la suma acumulada de los elementos del array |

In [15]:
print(f"vector: {vector}")
print(f"Máximo: {vector.max()}")
print(f"Índice del máximo: {vector.argmax()}")
print(f"Mínimo: {vector.min()}")
print(f"Índice del mínimo: {vector.argmin()}")
print(f"Suma: {vector.sum()}")
print(f"Media: {vector.mean()}")
print(f"Desviación: {vector.std():.3f}")
print(f"Suma acumulada: {vector.cumsum()}")

vector: [2 1 5 3 7 4 6 8]
Máximo: 8
Índice del máximo: 7
Mínimo: 1
Índice del mínimo: 1
Suma: 36
Media: 4.5
Desviación: 2.291
Suma acumulada: [ 2  3  8 11 18 22 28 36]


<h3 style="color: #d60e8c;">Otras operaciones</h3>

| Método | Descripción |
| :-- | :-- |
| sort | Devuelve otro array con los elementos ordenados|
| unique  | Devuelve otro array con los elementos, sin los repetidos (y puede devolver también las posiciones)|
| flip  | Da la vuelta al array|


In [16]:
print(f"vector antes de sort:   {vector}")
ordenado = np.sort(vector)
print(f"vector después de sort: {vector}")
print(f"ordenado: {ordenado}")

vector antes de sort:   [2 1 5 3 7 4 6 8]
vector después de sort: [2 1 5 3 7 4 6 8]
ordenado: [1 2 3 4 5 6 7 8]


Con listas es distinto, se modifica la propia lista:

In [17]:
lista = [4,5,7,1]
print(f"lista antes de sort:   {lista}")
lista.sort()
print(f"lista después de sort: {lista}")

lista antes de sort:   [4, 5, 7, 1]
lista después de sort: [1, 4, 5, 7]


In [18]:
vector2 = np.array([3,4,5,6,6,3,1])

unicos, posiciones = np.unique(vector2, return_index=True)
print(f"vector2:    {vector2}")
print(f"unicos:     {unicos}")
print(f"posiciones: {posiciones}")

vector2:    [3 4 5 6 6 3 1]
unicos:     [1 3 4 5 6]
posiciones: [6 0 1 2 3]


In [19]:
reflejado = np.flip(vector)

print(f"vector:    {vector}")
print(f"reflejado: {reflejado}")

vector:    [2 1 5 3 7 4 6 8]
reflejado: [8 6 4 7 3 5 1 2]


<a name="matrices"></a>
<h2 style="color: #d60e8c;">Matrices</h2>
<hr style="border: 0.5px solid #d60e8c;">

A partir de la matriz A, que creamos a continuación, veremos como acceder a los elementos de la matriz:

In [20]:
A = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

Usamos los corchetes para acceder a los distintos elementos del array. En la figura siguiente, se muestra la correspondencia entre la representación del array 2D como lista de listas y en forma de matrix 3x3:

<img src="notebooks-img/NumTwoEg.png" width="500" />

Podemos acceder al elemento de la 2ª columna - 3ª fila como se muestra en la figura siguiente:

<img src="notebooks-img/NumTwoFT.png" width="400" />

Usamos los corchetes para indicar los índices de fila y columna del elemento que queremos:

In [21]:
# Elemento de la segunda fila y tercera columna
A[1, 2]

23

 Considerando los elementos mostrados en la siguiente figura:

<img src="notebooks-img/NumTwoFF.png" width="400" />

Podemos acceder a los elementos de la siguiente forma:

In [22]:
# Acceso al elemento de la primera fila y primera columna
A[0, 0]

11

También podemos utilizar <i>slicing</i> en los arrays NumPy. Considerando la siguiente figura, si queremos obtener los elementos de la dos primeras columnas en la primera fila:

<img src="notebooks-img/NumTwoFSF.png" width="400" />

 Podemos hacerlo de la siguiente forma:

In [24]:
# Acceso los elemenos de la primera fila que están en la primera y segunda columna

A[0, 0:2]

array([11, 12])

De la misma forma, podemos obtener dos filas de la tercera columna:

In [25]:
# Acceso a los elementos de la segunda y tercera fila en la tercera columna
A[1:3, 2]

array([23, 33])

Son los elementos marcados en la figura siguiente: 

<img src="notebooks-img/NumTwoTST.png" width="400" />

In [26]:
# Acceso a todos los elementos de la primera fila:
A[0, :]

array([11, 12, 13])

In [27]:
# Acceso a todos los elementos de la primera columna:
A[:, 0]

array([11, 21, 31])

In [28]:
# Acceso a una submatriz:
A[0:2, 0:2]

array([[11, 12],
       [21, 22]])

<h3 style="color: #d60e8c;">Recorrer todos los elementos de una matriz</h3>

Por tanto, podríamos recorrer la matriz con dos bucles anidados, uno para recorrer las filas y otro para recorrer las columnas de cada fila. El siguiente programa recorre la matriz A y muestra sus elementos por pantalla:

In [29]:
filas, columnas = A.shape

for i in range(filas):  
    for j in range(columnas):  
        print(A[i,j], end=" ") # Muestra el elemento y un espacio a continuación
    print() # Para mostrar un salto de línea entre cad fila


11 12 13 
21 22 23 
31 32 33 


<a name="opmatrices"></a>
<h2 style="color: #d60e8c;">Operaciones con matrices</h2>
<hr style="border: 0.5px solid #d60e8c;">

<h3 style="color: #d60e8c;">Suma de matrices</h3>

Podemos sumar arrays NumPy de la misma forma que sumamos matrices. La suma de matrices de <code>X</code> e <code>Y</code> se muestra a continuación:

<img src="notebooks-img/NumTwoAdd.png" width="500" />

Los arrays NumPy correspondientes a <code>X</code> e <code>Y</code>:

In [31]:
# Creación de un array NumPy X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [32]:
# Creación de un array NumPy Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

Podemos sumarlos de la siguiente forma:

In [33]:
# Suma de X e Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

<h3 style="color: #d60e8c;">Multiplicación por un escalar</h3>

La multiplicación de un array NumPy por un escalar también es idéntica a multiplicar una matriz por un escalar. Si multiplicamos la matriz <code>Y</code> por el escarlar 2, simplemente multiplicamos cada elemento de la matriz por 2, como se muestra en la figura siguiente:

<img src="notebooks-img/NumTwoDb.png" width="500" />

Podemos hacer la misma operación con NumPy de la siguiente forma:

In [34]:
# Creamos un array NumPy Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [35]:
# Multiplicamos Y por 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

<h3 style="color: #d60e8c;">Traspuesta de una matriz</h3>

Podemos usar el atributo <code>T</code> para calcular la matriz traspuesta

In [36]:
# Creamos una matriz C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [37]:
# Obtenemos la traspuesta de C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

<h3 style="color: #d60e8c;">Resta de matrices</h3>

In [38]:
X - Y

array([[-1, -1],
       [-1, -1]])

<h3 style="color: #d60e8c;">Multiplicación de los elementos de dos matrices</h3>

In [39]:
X * Y

array([[2, 0],
       [0, 2]])

<h3 style="color: #d60e8c;">División de los elementos de dos matrices</h3>

In [40]:
X / Y

array([[0.5, 0. ],
       [0. , 0.5]])

<h3 style="color: #d60e8c;">Multiplicación de matrices</h3>

<img src="notebooks-img/NumMultMat.png" width="800" />

In [41]:
X @ Y

array([[2, 1],
       [1, 2]])

<a name="ejemplo"></a>
<h2 style="color: #d60e8c;">Ejemplo de ejercicio con matrices</h2>
<hr style="border: 0.5px solid #d60e8c;">


Ejemplo, paso a paso, de programa que calcula la suma y la media de las filas de una matriz utilizando operaciones de arrays de NumPy.


1. Pedimos la dimensión de la matriz, es decir, el número de filas y columnas:

In [42]:
filas = int(input("Número de filas de la matriz (>0):"))
while filas < 1:
    filas = int(input("Número de filas de la matriz(>0):"))

columnas = int(input("Numero de columnas de la matriz(>0): "))
while columnas < 1:    
    columnas = int(input("Numero de columnas de la matriz(>0): "))

print(f"Filas: {filas}")
print(f"Columnas: {columnas}")


Filas: 3
Columnas: 4


2. Creamos una matriz vacía con elementos de tipo entero:

In [43]:
matriz = np.empty((filas,columnas), dtype=np.int64)

3. Pedimos al usuario los elementos de la matriz y asignamos el valor a la matriz en la posición correspondiente:

In [44]:
for i in range(filas):
    for j in range(columnas):
        elemento = int(input(f"Introduce un valor para matriz[{i},{j}]: "))
        matriz[i,j] = elemento

print(matriz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


4. Creamos una lista con las suma de cada fila y otra lista con la media de cada fila utilizando las operaciones sobre arrays de NumPy:

In [47]:
lista_sumas = []
lista_medias = []
for fila in matriz:    
    # Cada fila de la matriz es un array -> podemos usas las operaciones de arrays
    lista_sumas.append(fila.sum()) 
    lista_medias.append(fila.mean())

5. Mostramos las listas:

In [46]:
print("Lista sumas: ")
for elemento in lista_sumas:
    print(elemento, end= " ")

print()
print("Lista medias:")
for elemento in lista_medias:
    print(elemento, end=" ")

Lista sumas: 
10 26 42 
Lista medias:
2.5 6.5 10.5 

<h3 style="color: #d60e8c;">Programa completo (sin funciones)</h3>

In [48]:
"""Programa que calcula la suma y la media de las filas de una matriz utilizando operaciones de arrays de NumPy"""

# Pide al usuario número de filas y columnas
filas = int(input("Número de filas de la matriz (>0):"))
while filas < 1:
    filas = int(input("Número de filas de la matriz(>0):"))

columnas = int(input("Numero de columnas de la matriz(>0): "))
while columnas < 1:    
    columnas = int(input("Numero de columnas de la matriz(>0): "))

# Crea matriz y rellana con los valores pedidos al usuario
matriz = np.empty((filas,columnas), dtype=np.int64)
for i in range(filas):
    for j in range(columnas):
        elemento = int(input(f"Introduce un valor para matriz[{i},{j}]: "))
        matriz[i,j] = elemento

# Crea las listas con las sumas y las medias
lista_sumas = []
lista_medias = []
for fila in matriz:    
    lista_sumas.append(fila.sum())
    lista_medias.append(fila.mean())

# Muestra la lista de sumas
print("Lista sumas: ")
for elemento in lista_sumas:
    print(elemento, end= " ")
print() # Para hacer un salto de línea

# Muestra la lista de medias
print("Lista medias:")
for elemento in lista_medias:
    print(elemento, end=" ")
print() # Para hacer un salto de línea

Lista sumas: 
10 26 42 
Lista medias:
2.5 6.5 10.5 


<h3 style="color: #d60e8c;">Programa completo (con funciones)</h3>

In [51]:
"""Programa que calcula la suma y la media de las filas de una matriz utilizando operaciones de arrays de NumPy"""

def pedir_natural(msg):
    num = int(input(f"{msg} (>0): "))
    while num<1:
        num = int(input(f"{msg} (>0): "))
    return num

def crear_y_rellenar_matriz(filas, columnas):
    matriz = np.empty((filas,columnas), dtype=np.int64)
    for i in range(filas):
        for j in range(columnas):
            elemento = int(input(f"Introduce un valor para matriz[{i},{j}]: "))
            matriz[i,j] = elemento    
    return matriz    

def crear_listas_sumas_medias(matriz):
    lista_sumas = []
    lista_medias = []
    for fila in matriz:    
        lista_sumas.append(fila.sum())
        lista_medias.append(fila.mean())    
    return lista_sumas, lista_medias

def mostrar_lista(lista):
    for elemento in lista:
        print(elemento, end=" ")
    print() # Para hacer un salto de línea


def main():
    filas = pedir_natural("Introduce el número de filas de la matriz")
    columnas = pedir_natural("Introduce el número de columans de la matriz")
    
    matriz = crear_y_rellenar_matriz(filas, columnas)
    sumas, medias = crear_listas_sumas_medias(matriz)

    print("Lista de sumas: ")
    mostrar_lista(sumas)
    print("Lista de medias: ")
    mostrar_lista(medias)


if __name__ == "__main__":
    main()

Lista de sumas: 
10 26 42 
Lista de medias: 
2.5 6.5 10.5 


<h3 style="color: #d60e8c;">Otra forma de calcular las sumas y medias de las filas</h3>

Se puede hacer el cálculo de la suma y media de cada fila sin utilizar NumPy. Es la forma que habría que utilizar cuando no exista una operación de NumPy predefinida. Se trata de recorrer la matriz de la forma vista en la primera parte de esta cuaderno.

In [52]:
def crear_listas_sumas_medias_v2(matriz):
    lista_sumas = []
    lista_medias = []
    filas, columnas = matriz.shape
    for i in range(filas):  
        suma_fila = 0
        for j in range(columnas):  
            suma_fila = suma_fila + matriz[i,j]
        lista_sumas.append(suma_fila)
        lista_medias.append(suma_fila/columnas)    
    
    return lista_sumas, lista_medias

<h3 style="color: #d60e8c;">Programa completo utilizando las dos formas de obtener sumas y medias</h3>

In [55]:
"""Programa que calcula la suma y la media de las filas de una matriz.
El cálculo se realiza de dos formas:
- Utilizando operaciones de arrays de NumPy
- Recorriendo cada fila para obtener la suma y la media.
"""

def pedir_natural(msg):
    """Pide un número natural al usuario"""
    num = int(input(f"{msg} (>0): "))
    while num<1:
        num = int(input(f"{msg} (>0): "))
    return num

def crear_y_rellenar_matriz(filas, columnas):
    """Crear una matriz vacía de una dimensión determinada y pide los elementos al usuario"""
    matriz = np.empty((filas,columnas), dtype=np.int64)
    for i in range(filas):
        for j in range(columnas):
            elemento = int(input(f"Introduce un valor para matriz[{i},{j}]: "))
            matriz[i,j] = elemento    
    return matriz    

def crear_listas_sumas_medias(matriz):
    """Calcula listas de sumas y medias con operaciones de NumPy"""
    lista_sumas = []
    lista_medias = []
    for fila in matriz:    
        lista_sumas.append(fila.sum())
        lista_medias.append(fila.mean())    
    return lista_sumas, lista_medias

def crear_listas_sumas_medias_v2(matriz):
    """Calcula listas de sumas y medias sin utilizar NumPy"""
    lista_sumas = []
    lista_medias = []
    filas, columnas = matriz.shape
    for i in range(filas):  
        suma_fila = 0
        for j in range(columnas):  
            suma_fila = suma_fila + matriz[i,j]
        lista_sumas.append(suma_fila)
        lista_medias.append(suma_fila/columnas)    
    
    return lista_sumas, lista_medias    

def mostrar_lista(lista):
    """Muestra por pantalla los elementos de una lista separados por espacios"""
    for elemento in lista:
        print(elemento, end=" ")
    print() # Para hacer un salto de línea

def main():
    """Función que encapsula el programa principal"""
    filas = pedir_natural("Introduce el número de filas de la matriz")
    columnas = pedir_natural("Introduce el número de columans de la matriz")
    
    matriz = crear_y_rellenar_matriz(filas, columnas)
    sumas, medias = crear_listas_sumas_medias(matriz)
    sumas2, medias2 = crear_listas_sumas_medias_v2(matriz)

    print("Cálculo CON NumPy ")
    print("----------------- ")
    print("Lista de sumas: ")
    mostrar_lista(sumas)
    print("Lista de medias: ")
    mostrar_lista(medias)
    print()
    print("Cálculo SIN NumPy ")
    print("----------------- ")
    print("Lista de sumas: ")
    mostrar_lista(sumas2)
    print("Lista de medias: ")
    mostrar_lista(medias2)


if __name__ == "__main__":
    main()

Cálculo CON NumPy 
----------------- 
Lista de sumas: 
10 26 42 
Lista de medias: 
2.5 6.5 10.5 
Cálculo SIN NumPy 
----------------- 
Lista de sumas: 
10 26 42 
Lista de medias: 
2.5 6.5 10.5 


<br/>
<hr style="border: 0.5px solid #d60e8c;">

<div style="float:left;">
INFORMÁTICA
</div>
<div style="text-align:right;">
Grados en Ing. Mecánica e Ing. en Tecnologías Industriales
</div>